services:
  backend:
    build:
      context: ./app/backend
    image: forgeflow-backend:0.3
    container_name: forgeflow-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: forgeflow
      DB_USER: forgeflow
      DB_PASSWORD: forgeflow_password
    ports:
      - "3000:3000"
    
    depends_on:
    - postgres
    networks:
      - forgeflow-network

  postgres:
    image: postgres:16
    container_name: forgeflow-postgres
    environment:
      POSTGRES_USER: forgeflow
      POSTGRES_PASSWORD: forgeflow_password
      POSTGRES_DB: forgeflow
    ports:
      - "5432:5432"
    restart: always
    networks:
      - forgeflow-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U forgeflow -d forgeflow"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  forgeflow-network:
    driver: bridge
volumes:
  postgres_data:
    driver: local